version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/project
hooks:
  BeforeInstall:
    - location: infra/codedeploy/appscpec/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: infra/codedeploy/appscpec/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: infra/codedeploy/appscpec/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: infra/codedeploy/appscpec/stop_server.sh
      timeout: 300
      runas: root